USE BANCO
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='CLIENTE' AND XTYPE='U')
CREATE TABLE CLIENTE(
CID VARCHAR(3),
CNOMBRE VARCHAR(30),
CCALLE VARCHAR(30),
CCIUDAD VARCHAR(50),
CONSTRAINT PK_CID PRIMARY KEY (CID)
)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='SUCURSAL' AND XTYPE='U')
CREATE TABLE SUCURSAL(
NOMBRESUCURSAL VARCHAR(30),
CIUDADSUCURSAL VARCHAR(30),
ACTIVOS DECIMAL(10,3),
CONSTRAINT PK_NOMBRESUCURSAL PRIMARY KEY (NOMBRESUCURSAL),
)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='CUENTA' AND XTYPE='U')
CREATE TABLE CUENTA(
NUMCUENTA VARCHAR(5),
NOMBRESUCURSAL VARCHAR(30),
SALDO DECIMAL(10,2),
CONSTRAINT PK_NUMCUENTA PRIMARY KEY(NUMCUENTA),
CONSTRAINT FK_CNS FOREIGN KEY(NOMBRESUCURSAL) REFERENCES SUCURSAL(NOMBRESUCURSAL) 
ON UPDATE CASCADE
ON DELETE CASCADE
)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='IMPOSITOR' AND XTYPE='U')
CREATE TABLE IMPOSITOR(
CID VARCHAR(3),
NUMCUENTA VARCHAR(5),
CONSTRAINT FK_IID_CID FOREIGN KEY(CID) REFERENCES CLIENTE(CID) 
ON UPDATE CASCADE
ON DELETE CASCADE,
CONSTRAINT FK_INC_CNC FOREIGN KEY(NUMCUENTA) REFERENCES CUENTA(NUMCUENTA) 
ON UPDATE CASCADE
ON DELETE CASCADE

)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='PRESTAMO' AND XTYPE='U')
CREATE TABLE PRESTAMO(
NUMPRESTAMO VARCHAR(4),
NOMBRESUCURSAL VARCHAR(30),
IMPORTE DECIMAL(10,3),
CONSTRAINT PK_NUMPRESTAMO PRIMARY KEY (NUMPRESTAMO),
CONSTRAINT FK_PNS FOREIGN KEY(NOMBRESUCURSAL) REFERENCES SUCURSAL(NOMBRESUCURSAL) 
ON UPDATE CASCADE
ON DELETE CASCADE

)
GO

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='PRESTATARIO' AND XTYPE='U')
CREATE TABLE PRESTATARIO(
CID VARCHAR(3),
NUMPRESTAMO VARCHAR(4),
CONSTRAINT FK_PID_CID FOREIGN KEY(CID) REFERENCES CLIENTE(CID) 
ON UPDATE CASCADE
ON DELETE CASCADE,
CONSTRAINT FK_PRNP_PNP FOREIGN KEY(NUMPRESTAMO) REFERENCES PRESTAMO(NUMPRESTAMO) 
ON UPDATE CASCADE
ON DELETE CASCADE

)
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='PAGO' AND XTYPE='U')
CREATE TABLE PAGO(
NUMPRESTAMO VARCHAR(4),
NUMPAGO INT,
FXPAGO DATE,
IMPORTEPAGO DECIMAL(10,3),
CONSTRAINT PK_PP PRIMARY KEY (NUMPRESTAMO,NUMPAGO),
CONSTRAINT FK_PP FOREIGN KEY(NUMPRESTAMO) REFERENCES PRESTAMO(NUMPRESTAMO) 
ON UPDATE CASCADE
ON DELETE CASCADE
)





