USE BANCO
GO
SELECT * FROM CLIENTE
GO
SELECT * FROM CLIENTE WHERE CCALLE='Mayor' 
OR CCALLE='Ramblas'
GO
SELECT * FROM PRESTAMO
GO
SELECT * FROM PRESTAMO 
WHERE NOMBRESUCURSAL='Navacerrada'
GO
SELECT * FROM CLIENTE
GO
SELECT * FROM CLIENTE WHERE CCIUDAD='León'
GO
SELECT * FROM CUENTA ORDER BY NUMCUENTA
GO
SELECT A.CID,C.CNOMBRE, B.NUMCUENTA,B.NOMBRESUCURSAL,B.SALDO FROM CUENTA B 
INNER JOIN (IMPOSITOR A  INNER JOIN CLIENTE C ON A.CID=C.CID)ON B.NUMCUENTA= A.NUMCUENTA  WHERE B.SALDO>350 
union
SELECT A.CID,C.CNOMBRE, B.NUMPRESTAMO,B.NOMBRESUCURSAL,B.IMPORTE FROM PRESTAMO B 
INNER JOIN (PRESTATARIO A  INNER JOIN CLIENTE C ON A.CID=C.CID)ON B.NUMPRESTAMO= A.NUMPRESTAMO  WHERE B.IMPORTE>850 
GO

SELECT * FROM CLIENTE, PRESTATARIO, PRESTAMO
IN(SELECT PRESTATARIO.CID FROM PRESTATARIO WHERE NOT EXISTS(SELECT * FROM IMPOSITOR WHERE IMPOSITOR.CID = PRESTATARIO.CID))

GO

SELECT * FROM IMPOSITOR
GO
SELECT * FROM PRESTATARIO
GO

SELECT IMPOSITOR.CID FROM IMPOSITOR INTERSECT SELECT PRESTATARIO.CID FROM PRESTATARIO



SELECT CLIENTE.CNOMBRE FROM CLIENTE WHERE CLIENTE.CCALLE='Mayor' or CLIENTE.CCIUDAD='Peguerinos'
go

-- Ejercicio 10
SELECT IMPOSITOR.CID, CLIENTE.CNOMBRE,IMPOSITOR.NUMCUENTA, CUENTA.SALDO
FROM CLIENTE INNER JOIN (IMPOSITOR INNER JOIN CUENTA ON IMPOSITOR.NUMCUENTA=CUENTA.NUMCUENTA)ON CLIENTE.CID=IMPOSITOR.CID